"""Provide constants used in other modules"""

RANK = "Rank"
TITLE = "Title"
DEVELOPER = "Developer"
PLATEFORMS = "Platforms"
AVERAGE_RATING = "Average Rating"
NB_RATINGS = "Number of Ratings"
URL = "URL"
ORIGINAL_TITLE = "Original Title"
YEAR = "Year"
RELEASE_DATE = "Release Date"
PICTURE_URL = "Picture URL"
GENRE = "Genre"
DESCRIPTION = "Description"
AUTHOR = "Author"
NB_SONGS = "Number of Songs"
ARTIST = "Artist"
LENGTH = "Length"
PRODUCER = "Producer"
NB_SEASONS = "Number of Seasons"
